name: Build and Push Nginx Docker Image

on:
  push:
    paths:
      - 'docker/nginx/**'
      - '.github/workflows/docker-nginx-build.yaml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nginx-demo
  IMAGE_TAG: ${{ github.GITHUB_SHA}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # Checkout the repository
      - name: Checkout Repo to runner
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get short SHA and Output
        run: |
           echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
           # This pushes imagetag variable with the build SHA out to env
           echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
           echo $GHA_SHA


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        id: load
        uses: docker/build-push-action@v3
        with:
          context: docker/nginx
          push: false
          load: true
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY}}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          labels: ${{ steps.meta.outputs.labels }}

      - name: Print generated tags
        run: echo "Generated tags  ${{ steps.meta.outputs.tags }}"


      - uses: lacework/lw-scanner-action@v1.4.3
        name: Scan container images for vulnerabitilies using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_INLINESCANNER_TOKEN }}
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY}}/${{ env.IMAGE_NAME }}
          # Default github environment variable wouldnt work here - stuffing imagetag as the TAG           
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

          SAVE_RESULTS_IN_LACEWORK: true
          RESULTS_IN_GITHUB_SUMMARY: true

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: docker/nginx
          push: true
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY}}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      #- name: Generate artifact attestation
      #  uses: actions/attest-build-provenance@v1
      #  with:
      #    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #    subject-digest: ${{ steps.push.outputs.digest }}
      #    push-to-registry: true