name: Build and Push Nginx Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'docker/nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repo to runner
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image (repository name must be lowercase)
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository | toLower }}/nginx:latest \
                       -t ghcr.io/${{ github.repository | toLower }}/nginx:${{ github.sha }} \
                       ./docker/nginx

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository | toLower }}/nginx:latest
          docker push ghcr.io/${{ github.repository | toLower }}/nginx:${{ github.sha }}