name: Terraform Destroy Workflow

on:
  workflow_dispatch:

jobs:
  destroy_infra:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repo to runner
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::680354150194:role/abenesh-github-test-Role-Vc5qXOXnQQ3L
          
      - name: Initialise Terraform and destroy Application infrastructure
        run: |
          cd application
          terraform fmt
          terraform init
          terraform destroy -var='example_api_key=${{ secrets.EXAMPLE_API_KEY }}' --auto-approve=true

      - name: Initialise Terraform and destroy EKS infrastructure
        run: |
          cd eks
          terraform fmt
          terraform init
          terraform destroy -var='example_api_key=${{ secrets.EXAMPLE_API_KEY }}' --auto-approve=true

